version: '3'
services:
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - '5432:5432'
  queue:
    image: redis
    container_name: queue
    restart: always
    ports:
      - '6379:6379'
