on:
  pull_request:
    branches: [ develop, main ]
jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure LTS node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Format and Lint
        run: |
          yarn install
          yarn format
          yarn lint
