name: merge-main

on:
  push:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: configure LTS node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: build, test, coverage
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test
        run: |
          yarn install
          yarn prisma generate
          yarn prisma migrate dev
          yarn test:e2e
          yarn build      
  version-release:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure LTS node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Version a Release
        run: |
          npm install -g semantic-release             \
          "@semantic-release/github"                  \
          "@semantic-release/changelog"               \
          "@semantic-release/commit-analyzer"         \
          "@semantic-release/release-notes-generator"
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
